version: '3'

services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: vue-app
  ports:
   - "5001:5001"
  networks:
   - backend_my-network

networks:
 backend_my-network:
  external: true